# Identificadores del proyecto en SonarQube
sonar.projectKey=uce-safe-ride
sonar.projectName=UCE Safe Ride Backend

# Directorio principal donde están los 10 microservicios
sonar.sources=backend/services

# Archivos que SonarQube debe ignorar para no ensuciar las métricas
sonar.exclusions=**/venv/**, **/.pytest_cache/**, **/__pycache__/**, **/tests/**, **/alembic/**

# Rutas a los reportes de cobertura (Añade aquí los XML de los servicios que vayas completando)
sonar.python.coverage.reportPaths=backend/services/student-service/coverage.xml, backend/services/vehicle-service/coverage.xml

# Rutas a los archivos de tests (opcional, ayuda a Sonar a categorizarlos)
sonar.tests=backend/services
sonar.test.inclusions=**/tests/test_*.py